eNET: Fix undefined reference to `monitor_flash_len'
commit 46b564bbfa08023de57a9e7daa270fb027cbfe1c removed the definition of
monitor_flash_len from the eNET which was not picked up due to extensive
use of the SRAM configuration target for testing

Signed-off-by: Graeme Russ <graeme.russ@gmail.com>