am335x, guardian: fix spl usb-eth boot
- On Guardian board, usb-eth boot in SPL stage fails due to certain
   misconfiguration. Hence, add the same to fix the issue.

 - configs are set based on the conditional statement present in
   arch/arm/mach-omap2/am33xx/board.c

 - disable tiny printf in SPL stage:
    As the library is optimized, the ability to deal with ethaddr is lost.
    The following message would be printed on the console,

    Error: flags type check failure for "ethaddr" <= "80a81144M" (type: m)
    Error inserting "ethaddr" variable, errno=1

Signed-off-by: Moses Christopher <BollavarapuMoses.Christopher@in.bosch.com>