Fix include/common.h for boards with CONFIG_STATUS_LED
The reordering of include/common.h by commit 274a0a1e4c78ab28 broke
boards with status LED support, resulting in
	error: #error Status LED configuration missing
errors. Undo this reordering to avoid this issue.

Signed-off-by: Wolfgang Denk <wd@denx.de>